baseURL = 'https://gimbu.netlify.app/'
languageCode = 'en'
title = 'Hugo Future Imperfect Slim'
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "default"
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStrech           = ""
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]

[params.meta]
	description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
	author              = "HTML5UP and Hugo"
	favicon             = false
	svg                 = true
	faviconVersion      = "1"
	msColor             = "#ffffff"
	iOSColor            = "#ffffff"

[params.header]
	navbarTitle         = "Future Imperfect"
	dynamicTitles       = true
	searchMenu          = true
	shareMenu           = true
	languageMenu        = true


[params.intro]
	header                = "Hugo Future Imperfect Slim"
	paragraph             = "Another fine, responsive site template by <a href='http://html5up.net'>HTML5 UP</a>."
	rssIntro              = true
	socialIntro           = true
	hideWhenSingleColumn  = false
	alwaysOnHomepage      = false

	[params.intro.pic]
		src                 = "/img/main/logo.jpg"
		shape               = "circle"
		width               = ""
		alt                 = "Hugo Future Imperfect Slim"

[params.sidebar]
  about               = "This theme was developed for Hugo static site generator."
  postAmount          = 5
  categories          = true
  categoriesByCount   = true

[params.footer]
  rssFooter           = true
  socialFooter        = true

[params.staticman]
  enabled             = false
  api                 = ""  # No Trailing Slash
  gitProvider         = "github"
  username            = ""
  repo                = ""
  branch              = ""

  [params.staticman.recaptcha]
    siteKey           = ""
    encryptedKey      = ""

[menu]

	[[menu.main]]
		name              = "Home"
		identifier        = "home"
		url               = "/"
		pre               = "<i class='fa fa-home'></i>"
		weight            = 1

	[[menu.main]]
		name              = "About"
		identifier        = "about"
		url               = "/about/"
		pre               = "<i class='far fa-id-card'></i>"
		weight            = 2

[Languages]

	[Languages.en]
		LanguageCode        = "en"
		LanguageName        = "English"
		weight              = 1

	[Languages.ko]
		LanguageCode        = "ko"
		LanguageName        = "한국어"
		title               = "한국어 페이지"
		description         = "어쩌구저쩌구"
		weight              = 2

		[[Languages.ko.menu.main]]
		name              = "홈"
		identifier        = "home"
		url               = "/"
		pre               = "<i class='fas fa-home'></i>"
		weight            = 1

[social]
	# Coding Communities
	github                = "pacollins/hugo-future-imperfect-slim"
	gitlab                = ""
	stackoverflow         = "" # User Number
	bitbucket             = ""
