baseURL = 'https://gimbu.netlify.app/'
languageCode = 'ko'
title = 'woojoo'
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "default"
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStrech           = ""
  socialShare           = ["Instagram"]

[params.meta]
	description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
	author              = "HTML5UP and Hugo"
	favicon             = false
	svg                 = true
	faviconVersion      = "1"
	msColor             = "#ffffff"
	iOSColor            = "#ffffff"

[params.header]
	navbarTitle         = "woojoo"
	dynamicTitles       = true
	searchMenu          = true
	shareMenu           = true
	languageMenu        = false


[params.intro]
	header                = "낌부 싸이트"
	paragraph             = "<a href='https://www.instagram.com/coincidence_number/'>연수</a>가 <a href='https://www.instagram.com/seahorse_lee/'>예주</a> 자랑하려고 만든 사이트."
	rssIntro              = true
	socialIntro           = true
	hideWhenSingleColumn  = false
	alwaysOnHomepage      = false

	[params.intro.pic]
		src                 = "/img/main/main.jpeg"
		shape               = "circle"
		width               = ""
		alt                 = ""

[params.sidebar]
  about               = "테스트입니다ㅏㅏ"
  postAmount          = 5
  categories          = true
  categoriesByCount   = true

[params.footer]
  rssFooter           = true
  socialFooter        = true

[params.staticman]
  enabled             = false
  api                 = ""  # No Trailing Slash
  gitProvider         = "github"
  username            = ""
  repo                = ""
  branch              = ""

  [params.staticman.recaptcha]
    siteKey           = ""
    encryptedKey      = ""

[menu]

	[[menu.main]]
		name              = "Home"
		identifier        = "home"
		url               = "/"
		pre               = "<i class='fa fa-home'></i>"
		weight            = 1

	[[menu.main]]
		name              = "About"
		identifier        = "about"
		url               = "/about/"
		pre               = "<i class='far fa-id-card'></i>"
		weight            = 2


[social]
	# Coding Communities
	github                = "woocosmos/"
	gitlab                = ""
	stackoverflow         = "" # User Number
	bitbucket             = ""
